# Generated by Django 2.2.3 on 2019-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='archived',
            new_name='done',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(default='default', max_length=7),
        ),
    ]
